import Link from "next/link";
import { Zap } from "lucide-react";

export default function TermsOfServicePage() {
  const lastUpdated = "August 12, 2026";
  const appUrl = "https://astraweb-production.up.railway.app";
  const contactEmail = "legal@astra-intelligence.com";

  return (
    <div className="min-h-screen bg-gradient-to-br from-astra-950 via-slate-900 to-slate-950 text-white">
      <nav className="border-b border-white/10 px-6 py-4">
        <div className="max-w-4xl mx-auto flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-astra-500 flex items-center justify-center">
              <Zap className="w-4 h-4 text-white" />
            </div>
            <span className="font-bold text-lg">Astra Intelligence</span>
          </Link>
          <Link href="/login" className="text-sm text-white/60 hover:text-white transition">
            Sign in
          </Link>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-white/50 mb-12">Last updated: {lastUpdated}</p>

        <div className="prose prose-invert max-w-none space-y-8 text-white/80">

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
            <p>By accessing and using Astra Intelligence at {appUrl}, you accept and agree to be bound by these Terms of Service. If you do not agree, please do not use the platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">2. Description of Service</h2>
            <p>Astra Intelligence is an AI-powered marketing platform that helps businesses create content, manage campaigns, and publish to social media. The platform uses artificial intelligence to generate marketing content based on your brand guidelines and uploaded documents.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">3. User Accounts</h2>
            <p className="mb-3">You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Provide accurate and complete information when registering</li>
              <li>Keep your password secure and not share it with others</li>
              <li>Notify us immediately of any unauthorized use of your account</li>
              <li>Not create multiple accounts or use the platform to impersonate others</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use</h2>
            <p className="mb-3">You agree not to use Astra Intelligence to:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>Generate content that is illegal, harmful, threatening, or abusive</li>
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Distribute spam, malware, or phishing content</li>
              <li>Interfere with or disrupt the platform's services</li>
              <li>Attempt to gain unauthorized access to other accounts or systems</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">5. Content and Intellectual Property</h2>
            <p className="mb-3"><strong className="text-white">Your Content:</strong> You retain ownership of all content you upload and create using the platform. By using our service, you grant us a limited license to process and store your content solely to provide the service.</p>
            <p className="mb-3"><strong className="text-white">AI-Generated Content:</strong> Content generated by our AI based on your inputs belongs to you. You are responsible for reviewing AI-generated content before publishing.</p>
            <p><strong className="text-white">Platform:</strong> Astra Intelligence and its original content, features, and functionality are owned by us and are protected by intellectual property laws.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">6. Social Media Publishing</h2>
            <p className="mb-3">When you connect social media accounts and authorize publishing, you acknowledge that:</p>
            <ul className="list-disc list-inside space-y-2">
              <li>You are solely responsible for all content published through the platform</li>
              <li>Published content must comply with each social platform's terms of service</li>
              <li>We are not responsible for content moderation decisions made by social platforms</li>
              <li>You can disconnect accounts and revoke publishing permissions at any time</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">7. Disclaimers and Limitation of Liability</h2>
            <p className="mb-3">The platform is provided "as is" without warranties of any kind. We do not guarantee that AI-generated content will be accurate, appropriate, or effective for your specific needs. Always review content before publishing.</p>
            <p>To the maximum extent permitted by law, we shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the platform.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">8. Service Availability</h2>
            <p>We strive to maintain platform availability but do not guarantee uninterrupted access. We may perform maintenance, updates, or experience technical issues that temporarily affect service availability.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">9. Termination</h2>
            <p>We reserve the right to suspend or terminate accounts that violate these Terms. You may cancel your account at any time from the Settings page. Upon termination, your data will be deleted according to our Privacy Policy.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">10. Changes to Terms</h2>
            <p>We may update these Terms at any time. Continued use of the platform after changes constitutes acceptance of the new Terms. We will notify users of significant changes via email.</p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">11. Contact</h2>
            <p>For questions about these Terms, contact us at: <a href={`mailto:${contactEmail}`} className="text-astra-400 hover:text-astra-300">{contactEmail}</a></p>
          </section>

        </div>

        <div className="mt-12 pt-8 border-t border-white/10 flex items-center gap-6 text-sm text-white/40">
          <Link href="/" className="hover:text-white/70 transition">Home</Link>
          <Link href="/privacy" className="hover:text-white/70 transition">Privacy Policy</Link>
        </div>
      </main>
    </div>
  );
}
